create database if not exists `AvayaCdr`;
GRANT ALL ON `AvayaCdr`.* TO 'cdruser'@'%';
USE AvayaCdr;
CREATE TABLE if not exists `cdr` (
`id` INT(10) NOT NULL AUTO_INCREMENT,
`CallStart` DATETIME NULL DEFAULT NULL,
`ConnectedTime` TIME NULL DEFAULT NULL,
`RingTime` INT(11) NULL DEFAULT NULL,
`Caller` VARCHAR(50) NULL DEFAULT NULL,
`Direction` VARCHAR(50) NULL DEFAULT NULL,
`CalledNumber` VARCHAR(50) NULL DEFAULT NULL,
`DialledNumber` VARCHAR(50) NULL DEFAULT NULL,
`IsInternal` VARCHAR(50) NULL DEFAULT NULL,
`CallID` VARCHAR(50) NULL DEFAULT NULL,
`HoldTime` VARCHAR(50) NULL DEFAULT NULL,
`ParkTime` VARCHAR(50) NULL DEFAULT NULL,
`ExternalTargetingCause` VARCHAR(50) NULL DEFAULT NULL,
`ExternalTargeterId` VARCHAR(50) NULL DEFAULT NULL,
`ExternalTargetedNumber` VARCHAR(50) NULL DEFAULT NULL,
`CallerServerIP` VARCHAR(60) NULL DEFAULT '',
`UniqueCallIDCallerExtension` VARCHAR(50) NULL DEFAULT '',
`UniqueCallIDCalledParty` VARCHAR(50) NULL DEFAULT '',
`SMDRRecordingTime` DATETIME NULL DEFAULT NULL,
PRIMARY KEY (`id`)
);